import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";

import { Button } from "antd";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const router = useRouter();

  if (!sessionData || !sessionData.user) {
    return (
      <>
        <Head>
          <title>Kooperatywa</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Button onClick={() => void signIn()}>Zaloguj się</Button>
        </main>
      </>
    );
  }

  void router.push("/dashboard");
  return <></>;
};

export default Home;
